on: [push]

name: Azure Login

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          ${{ secrets.SuperSecret }}