on: [push]

name: Azure Login

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_SUB_MPN }}
      - run: |
          jq --version
        name: JQ Version
        env:
          AZURE_ENV: ${{ secrets.AZURE_SUB_MPN }}