on: [push]

name: Rancher Deploy

env:
  ARM_TENANT_ID: ${{ secrets.azureTenantId }}
  tf_version: 'latest'
  tf_working_dir: './rancher-rke-ha'

jobs:
  dev:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: 9fb3f95f-3d85-461a-b6ec-27451807a387
    steps:
      - name: "Git: Checkout Repo"
        uses: actions/checkout@v2
      - name: "SecretHub: Export envrionment-specific secrets"
        uses: secrethub/actions/env-export@v0.1.0
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.secretHubServiceAccount }}
          ARM_CLIENT_ID: secrethub://azure/demo/${{ github.job }}/clientId
          ARM_CLIENT_SECRET: secrethub://azure/demo/${{ github.job }}/clientSecret
      - name: "DEBUG: Print environment"
        run: env | sort
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
      - name: 'Terraform: Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'plan'
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
  prod:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: 623aabe5-748d-4b15-be89-3119e247a9fd
    steps:
      - name: "Git: Checkout Repo"
        uses: actions/checkout@v2
      - name: "SecretHub: Export envrionment-specific secrets"
        uses: secrethub/actions/env-export@v0.1.0
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.secretHubServiceAccount }}
          ARM_CLIENT_ID: secrethub://azure/demo/${{ github.job }}/clientId
          ARM_CLIENT_SECRET: secrethub://azure/demo/${{ github.job }}/clientSecret
      - name: "${{ github.job }}: Print environment"
        run: env | sort
      # - name: Print environment with masked secrets
      #   run: $AZURE_TEST_MGR
      - name: 'Terraform: Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
      - name: 'Terraform: Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'plan'
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
